// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDjV4LviAfe7_j7UMde-Yr2OZL44Dy_Bvo',
    appId: '1:859629915738:web:679ac175897d0fd39c1263',
    messagingSenderId: '859629915738',
    projectId: 'fintrack-8aaaf',
    authDomain: 'fintrack-8aaaf.firebaseapp.com',
    storageBucket: 'fintrack-8aaaf.firebasestorage.app',
    measurementId: 'G-1VXFGSD3MV',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyByoLKPdpgjIHqyHk6xcS21ZPHVspqp_cw',
    appId: '1:859629915738:android:0c1ed391845098379c1263',
    messagingSenderId: '859629915738',
    projectId: 'fintrack-8aaaf',
    storageBucket: 'fintrack-8aaaf.firebasestorage.app',
  );
}
